### ISSUE TITLE
Formatting option disappeared?

### ISSUE THREAD

**Issue by JordanCronin** [MicrosoftDocs/forms-pro#1]
It looks like the formatting options no longer appear. Is this a regression bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c486fb3-5db1-5d6a-45f8-b0b803fdd86f
* Version Independent ID: 10b85f4c-6388-f2c5-0101-459a1add35c0
* Content: [Format text in a survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/survey-text-format#feedback)
* Content Source: [fp-docs/survey-text-format.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/survey-text-format.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by ChrisPucci13** [comment]
hello ! Any update on why the text formatting option is no longer available?

**Comment by sbmjais** [comment]
Hi @JordanCronin, @ChrisPucci13: Thanks for contacting us.
Are the formatting options available now. If not, please contact Microsoft support to look into it.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
