### ISSUE TITLE
Response Capacity vs Licenses

### ISSUE THREAD

**Issue by lundcry** [MicrosoftDocs/forms-pro#10]
The explanation for response capacity vs number of licenses is confusing.   If I have 5 active Forms users, but 24,000 annual capacity is more than enough right now, does that mean we just need to purchase ONE add on with 5 licenses?  Or do we need to buy 5 add ons, one for each license, and have far more responses than we could use in a year?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eea885c-4244-1721-36f7-6a42baca9411
* Version Independent ID: 59ced40c-3cea-298e-ee4e-38c390493c59
* Content: [Purchase - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/purchase#feedback)
* Content Source: [fp-docs/purchase.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/purchase.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @lundcry - We have published a document update to the response consumption - [https://docs.microsoft.com/en-us/forms-pro/purchase#response-capacity-consumption](https://docs.microsoft.com/en-us/forms-pro/purchase#response-capacity-consumption). Please have a look and let us know if this helps.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
