### ISSUE TITLE
forms pro responses

### ISSUE THREAD

**Issue by JoellenMS** [MicrosoftDocs/forms-pro#12]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33886e55-fe3b-627c-cd2c-0782798f126b
* Version Independent ID: 52480bca-1cb6-5c8a-daae-9cc5fb1352ee
* Content: [Frequently asked questions - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/mfp-faq)
* Content Source: [fp-docs/mfp-faq.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/mfp-faq.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @JoellenMS, the feedback section is empty. Please share your feedback.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
