### ISSUE TITLE
Information isn't correct

### ISSUE THREAD

**Issue by dcodding** [MicrosoftDocs/forms-pro#15]
Assigned license on Forms Pro but not seeing anything different than original Forms and the information on this page related to opting out is also not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea68564-cac2-d24f-1731-a71f085fb66e
* Version Independent ID: 1ec1bad4-d164-8e46-2b9d-c16bf7513fd4
* Content: [Get started - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/get-started#feedback)
* Content Source: [fp-docs/get-started.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/get-started.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)
Closing this issue.
