### ISSUE TITLE
Customize the sender of the survey email

### ISSUE THREAD

**Issue by piyushpaliwal** [MicrosoftDocs/forms-pro#17]
Why has this section been removed from the documentation? Is the product group not supporting this change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe130e3-5f7e-f3af-4a5b-3dab02d7ec28
* Version Independent ID: 464ab2a9-0cb2-a920-b32b-a19ad9c8e8ab
* Content: [Send a survey by using email - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/send-survey-email#feedback)
* Content Source: [fp-docs/send-survey-email.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/send-survey-email.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks @piyushpaliwal for contacting us. This feature is temporarily unavailable. It is expected to be available by end of May 2020. We'll update the document accordingly.
Closing this issue.

**Comment by Sumaira995** [comment]
How do i change the forms pro default email ID?

**Comment by piyushpaliwal** [comment]
@Sumaira995 The only option at this time is to open up a support ticket with Microsoft. I think they are still taking requests for this feature, however, based on what I heard, they are going to GA this setting in May 2020.

**Comment by Sumaira995** [comment]
@piyushpaliwal Thanks for the info

**Comment by Sumaira995** [comment]
Why is it not possible to embed the email first question within shared mailbox?

**Comment by piyushpaliwal** [comment]
@Sumaira995 can you elaborate what you meant? Kinda hard to understand.

**Comment by Sumaira995** [comment]
Thanks for the response
I have created a flow which triggers like "When a case is marked as resolved in dynamics 365, it should send the survey to the customer"
The survey should be sent via shared mailbox
Its working fine in the way it should

But, when survey is sent via shared mailbox, it is not showing option to embed the form like how we usually embed first question in forms pro.

Instead, it only gives option to embed a link
