### ISSUE TITLE
Why is it not possible to embed the email first question within shared mailbox?

### ISSUE THREAD

**Issue by Sumaira995** [MicrosoftDocs/forms-pro#18]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4f3fffc-2fa5-c640-ea63-f97716a3e82d
* Version Independent ID: 80267beb-df34-a1a4-f423-b9c485d4efcb
* Content: [Survey settings - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/invite-settings)
* Content Source: [fp-docs/invite-settings.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/invite-settings.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@Sumaira995 - Please provide more details and contact the Support team. To contact Support, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)
Closing this issue.
