### ISSUE TITLE
Versions?

### ISSUE THREAD

**Issue by akel4uk** [MicrosoftDocs/forms-pro#19]
My version of Forms pro, does not have seem to have the same options described here, I need to translate my form into a few languages and I can work out how to do it!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4cb88d8-55a3-9e36-00c2-ab36509bd952
* Version Independent ID: 43d00b62-0c3c-332c-9f6c-047707ec3b07
* Content: [Create a multilingual survey - Microsoft Forms Pro](https://docs.microsoft.com/en-gb/forms-pro/create-multilingual-survey#feedback)
* Content Source: [fp-docs/create-multilingual-survey.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/create-multilingual-survey.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@akel4uk - Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)
Closing this issue.
