### ISSUE TITLE
Absolutely Brilliant !!!

### ISSUE THREAD

**Issue by RICCARDO-da-Vinci** [MicrosoftDocs/forms-pro#2]
I have just spent 3hrs entering data...but now the fun begins !
Simple question... which I couldn't find an answer to....
How many characters is allowed in a short answer option... and I suppose I would like to know how many in a long answer.... Ciao for now - Riccardo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f943a733-9295-0882-d3e1-21aaea5491e6
* Version Independent ID: c165bada-eea6-dd3d-dfb4-daffd9c47af8
* Content: [Create a new survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/create-new-survey#feedback)
* Content Source: [fp-docs/create-new-survey.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/create-new-survey.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Forms Pro is now Customer Voice. We have documented the character limits at: [Survey, question, response, and character limits](https://docs.microsoft.com/en-us/dynamics365/customer-voice/plan-survey#survey-question-response-and-character-limits
)
Closing this task for Forms Pro.
