### ISSUE TITLE
Metric for Total Responses at Tenant Level

### ISSUE THREAD

**Issue by barrcode** [MicrosoftDocs/forms-pro#20]
Where can I find the total number of responses received at the tenant level? We have a Dynamics 365 Enterprise licensed tenant which includes 2,000 responses for free. The challenge is to keep tabs on how many responses have been received in a given month. How will I know if we are close to or have exhausted our 2,000 free responses and need to purchase additional responses?

**Comment by sbmjais** [comment]
Thanks for your feedback. For product-related feedback, visit [UserVoice](https://microsoftforms.uservoice.com/forums/386451-welcome-to-microsoft-forms-suggestion-box?category_id=357997).
Closing this issue.
