### ISSUE TITLE
Multiple Choice Option Text

### ISSUE THREAD

**Issue by mediascope** [MicrosoftDocs/forms-pro#21]
I am unable edit the option text. Sometimes suggested "Yes", "No" or "Maybe" but some of answers remains options 1, options 2 etc.. I can add or remove the choices but unable to edit the text. Please advise how to fix this. Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f943a733-9295-0882-d3e1-21aaea5491e6
* Version Independent ID: c165bada-eea6-dd3d-dfb4-daffd9c47af8
* Content: [Create a new survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/create-new-survey#feedback)
* Content Source: [fp-docs/create-new-survey.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/create-new-survey.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@mediascope - I just checked and found that I was able to edit the option text as required. 
If you are still facing issues, please contact the Support team. To contact Support, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)
Closing this issue.
