### ISSUE TITLE
Embed Steps Please

### ISSUE THREAD

**Issue by donalmc** [MicrosoftDocs/forms-pro#23]
Could you please provide an actual set of steps for embedding the form.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f55b2c-5fac-5093-0036-1841350c0678
* Version Independent ID: e75c762b-102c-d0ab-fab1-be09acbf9342
* Content: [Embed a survey in a webpage - Microsoft Forms Pro](https://docs.microsoft.com/en-gb/forms-pro/embed-web-page#feedback)
* Content Source: [fp-docs/embed-web-page.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/embed-web-page.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @donalmc, we have provided an example of how to embed an inline survey - [Update a webpage's source code](https://docs.microsoft.com/en-us/forms-pro/embed-web-page#update-a-webpages-source-code). Please let me know if this solves your issue.

**Comment by donalmc** [comment]
Hi sbmjais - these are not steps - I just want to embed a survey in a website for anonymous collection. I don't need to pass variables back. For example, the article says 'You created a div container with the ID surveyDiv on the webpage where you want to display the survey" - when did I do this? - does the supplied code genearate the div or do I have to add it manaully? How big should the div be?

**Comment by sbmjais** [comment]
Hi @donalmc - The location and size of the div container depends on the webpage's design. The code that is generated in Forms Pro is the survey's embed code. The div container and a method to call the renderSurvey function must be defined manually. 

The generated code will always contain the default survey variables. For anonymous collection, you can remove the variables from the code. In this case, the survey will be treated as anonymous.

**Comment by nikguld** [comment]
Is it possible to change the name and color of the embedded website button? - we would like to use it on our website, but we do not like the standard name

**Comment by sbmjais** [comment]
Hi @nikguld - Yes, it is possible to change the name and color of the embedded website button.

To change the button name, update the **se.renderButton** function in the generated code. For example, if you want the button name to be "My survey button", update the **se.renderButton** function as: se.renderButton( context,"My survey button");

To change the button color, override the CSS of your website. For example, if you want to change the button color to purple, override the CSS as follows:
	<style>
	#MfpEmbed_Button {
		background-color: purple !important;
		}
	</style>

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
