### ISSUE TITLE
Add the information it´s necessary the powerbi pro license. 

### ISSUE THREAD

**Issue by tcardos0** [MicrosoftDocs/forms-pro#24]
Add the information it´s mandatory  the powerbi pro license. 

on the link: #connect-to-dynamics-365-customer-service-data

add the example http://contoso.crm.dynamics.com/  
#some customers add the API URL for odata. itpsa not work for the report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b68454-4087-41f6-e659-ea24af34654d
* Version Independent ID: 33d9037b-08c0-131c-b232-ed61533afdd8
* Content: [Customer Satisfaction app - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/customer-satisfaction-app#connect-to-dynamics-365-customer-service-data)
* Content Source: [fp-docs/customer-satisfaction-app.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/customer-satisfaction-app.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks @tcardos0. The updated help is published - [Connect to Dynamics 365 Customer Service data ](https://docs.microsoft.com/en-us/forms-pro/customer-satisfaction-app#connect-to-dynamics-365-customer-service-data).
Closing this issue.
