### ISSUE TITLE
No save and continue feature?

### ISSUE THREAD

**Issue by galaxy4public** [MicrosoftDocs/forms-pro#25]
For more than 3 years users are asking for the "Save & Continue" functionality in Forms, yet this feature is still not there.

It is really hard to sell Forms to the users when any large survey or form does not have this functionality.  For example, we are trialling the product to perform internal compliance checklists.  Each checklist could take an hour to complete and not everybody has enough time to do it in one go.  It is a pity that the feature is not there.  Even using the local storage in the browser to preserve the state upon return to the form would be more than welcome.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04edf6fe-cd0b-4eea-35ee-092bc6e3c6bc
* Version Independent ID: 32adfb55-c368-4aa8-1559-711c5c7664ab
* Content: [Data flow - Microsoft Forms Pro](https://docs.microsoft.com/en-gb/forms-pro/data-flow)
* Content Source: [fp-docs/data-flow.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/data-flow.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for your feedback. For product-related feedback, visit [UserVoice](https://microsoftforms.uservoice.com/forums/386451-welcome-to-microsoft-forms-suggestion-box?category_id=357997).
Closing this issue.
