### ISSUE TITLE
'Response capacity consumption' section is duplicated

### ISSUE THREAD

**Issue by ee61re** [MicrosoftDocs/forms-pro#26]
duplicate content on the page

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eea885c-4244-1721-36f7-6a42baca9411
* Version Independent ID: 59ced40c-3cea-298e-ee4e-38c390493c59
* Content: [Purchase Microsoft Forms Pro and additional license - Microsoft Forms Pro](https://docs.microsoft.com/en-gb/forms-pro/purchase#response-capacity-consumption)
* Content Source: [fp-docs/purchase.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/purchase.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks @ee61re for the feedback. We have updated the document.
