### ISSUE TITLE
No mention of permissions needed

### ISSUE THREAD

**Issue by gregowens** [MicrosoftDocs/forms-pro#27]
This page should acknowledge the permissions required to work with emails. I am D365 System Administrator. Historically this is "god mode" and allows full access. I could not edit email templates. A few weeks ago, trying to do so caused the generic "Sorry, something went wrong" error so I was granted "Survey Services Administrator" which resolved it. More recently, the ability to swap templates or save/save as was greyed out. I now need "Survey Owner" too. I found this by trial and error - please add a section on permissions! :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe130e3-5f7e-f3af-4a5b-3dab02d7ec28
* Version Independent ID: 464ab2a9-0cb2-a920-b32b-a19ad9c8e8ab
* Content: [Send a survey by using email - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/send-survey-email#customize-the-senders-email-address)
* Content Source: [fp-docs/send-survey-email.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/send-survey-email.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
We have a document for required privileges at: [Privileges required](https://docs.microsoft.com/en-us/forms-pro/choose-environment#privileges-required). Please see if this is the information you were looking for.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
