### ISSUE TITLE
Section 6 image needs replaced 

### ISSUE THREAD

**Issue by Steven-Knight** [MicrosoftDocs/forms-pro#28]
It says not at all likely on both ends of the scale. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f943a733-9295-0882-d3e1-21aaea5491e6
* Version Independent ID: c165bada-eea6-dd3d-dfb4-daffd9c47af8
* Content: [Create a new survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/create-new-survey#feedback)
* Content Source: [fp-docs/create-new-survey.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/create-new-survey.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback. We have corrected the image [here](https://docs.microsoft.com/en-us/forms-pro/create-new-survey).
Closing this issue.
