### ISSUE TITLE
Screenshots not optimized in create branch in a forms article

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/forms-pro#29]
The total number of and highlights on the screenshots do not seem to be optimized from the readability or scannability perspective. Are as many screenshots necessary? Are the weird red boxes to highlight UI areas necessary?
Please re-evaluate and fix it as necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147c85a2-7442-d63f-789c-719a67418b75
* Version Independent ID: 5af6f725-a4b6-c414-387a-eda7e2d9a5e8
* Content: [Create a branching rule for a survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/create-branching-rule#feedback)
* Content Source: [fp-docs/create-branching-rule.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/create-branching-rule.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for feedback @ashishguptaiitb. We will evaluate and fix as required. Closing this task.

**Comment by sbmjais** [comment]
Thanks for contacting us. I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by ashishguptaiitb** [comment]
Thank you @sbmjais . I believe you mean to say that it will be fixed in the future and is not yet fixed. Is the to-do item tracked elsewhere which is why you want this ticket closed? Asking as I don't know the issue workflow in place.
