### ISSUE TITLE
Forms pro is not working when we only enterprise license.

### ISSUE THREAD

**Issue by Sapeta** [MicrosoftDocs/forms-pro#3]
On this section "Disable Microsoft Forms Pro for a user"
 it is stating that microsoft Forms Pro is available to all the users who have a D365 enterprise license.

However it doesn’t work when you opted for a trail/paid license separately. In this scenario we have to assign both enterprise and forms pro license to have it working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eea885c-4244-1721-36f7-6a42baca9411
* Version Independent ID: 59ced40c-3cea-298e-ee4e-38c390493c59
* Content: [Purchase - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/purchase#feedback)
* Content Source: [fp-docs/purchase.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/purchase.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)
Closing this issue.
