### ISSUE TITLE
Forms Pro Survey disappearing from Shared With Me

### ISSUE THREAD

**Issue by colinbrislawn** [MicrosoftDocs/forms-pro#30]
Hello!

I'm following the instructions on [this page](https://docs.microsoft.com/en-us/forms-pro/share-survey-collaborate) to share a forms pro survey with members of my organization, like @Justinwright973. They can _usually_ open up the direct link and view the survey, but not always. And after sharing the link with them, the survey does not appear under the Shared with me tab in the Forms Pro homepage.

Is there a better way to share a Forms Pro Survey with a group or with a team or channel on Teams?

[The FAQ page](https://docs.microsoft.com/en-us/forms-pro/mfp-faq) says
>Group forms aren't currently supported in Microsoft Forms Pro.

Does this mean this functually is not supported? Any suggested workaround?

Thank you for any advice you have,
Colin

---

Possibly related issues:
[Not everyone seeing Group Forms](https://techcommunity.microsoft.com/t5/microsoft-forms/not-everyone-seeing-group-forms/m-p/1406347/highlight/false#M6092)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921d4180-f5c9-36f4-4d66-8760e2c3b046
* Version Independent ID: 951f92b7-b462-e064-2ff4-f1a934bd0f54
* Content: [Share a survey for collaborating - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/share-survey-collaborate)
* Content Source: [fp-docs/share-survey-collaborate.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/share-survey-collaborate.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for contacting us. The "Group forms" feature is not available in Forms Pro. For product-related feedback, visit [UserVoice](https://microsoftforms.uservoice.com/forums/386451-welcome-to-microsoft-forms-suggestion-box?category_id=357997).

If you would like to contact the Support team, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
