### ISSUE TITLE
Share as a Template missing from Forms Pro

### ISSUE THREAD

**Issue by sgu222e** [MicrosoftDocs/forms-pro#31]
Share as a Template missing from Forms Pro

Observed issue:
Starting around May 20th, my Forms Pro users no longer have the Share as a Template option on their forms. We have multiple users who create forms and share the templates with other users.
All users creating and sharing the forms have Forms Pro licences.

Desired Results:
Users with Forms Pro licences should be able to Share as a Template to other users on our tenant.

Steps to recreate:
1. Login to Forms Pro
2. Create a new form (Same results with existing forms)
3. Enter title, description and test question
4. Click the ellipsis (...)
5. Click on Share
Only Share to Collaborate is the only option presented, when you should also see Share as a Template. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0926425f-b502-db9e-694d-0cd97d051f16
* Version Independent ID: 8b93755c-9d22-072b-5d5b-debb6e8170f2
* Content: [Share a survey as a template - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/share-survey-template)
* Content Source: [fp-docs/share-survey-template.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/share-survey-template.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sgu222e** [comment]
> Same issue here! Have you resolved this?

No, I don't think MS reads this info at all

**Comment by beiLucas** [comment]
I am also having this problem Forms Pro not including a Share as Template option.

**Comment by sbmjais** [comment]
Thanks for contacting us. The "Share as template" feature is not available in Forms Pro. For product-related feedback, visit [UserVoice](https://microsoftforms.uservoice.com/forums/386451-welcome-to-microsoft-forms-suggestion-box?category_id=357997).

If you would like to contact the Support team, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
