### ISSUE TITLE
Error in diagram for Q2. Step 6 of Create a new survey

### ISSUE THREAD

**Issue by scott-jackson-mpe** [MicrosoftDocs/forms-pro#33]
I have spotted an error in the diagram for create a survey as the diagram for Step 6, question 2 on the diagram it has the labels for 0 being Not at all likely, and the same label for 10 where as it should be something like Highly likely.
https://docs.microsoft.com/en-us/forms-pro/create-new-survey#create-a-new-survey-with-forms-pro 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f943a733-9295-0882-d3e1-21aaea5491e6
* Version Independent ID: c165bada-eea6-dd3d-dfb4-daffd9c47af8
* Content: [Create a new survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/create-new-survey)
* Content Source: [fp-docs/create-new-survey.md](https://github.com/MicrosoftDocs/forms-pro/blob/live/fp-docs/create-new-survey.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback. We have corrected the image [here](https://docs.microsoft.com/en-us/forms-pro/create-new-survey).
Closing this issue.
