### ISSUE TITLE
Embedding the form in a Modal

### ISSUE THREAD

**Issue by akirby** [MicrosoftDocs/forms-pro#34]
Hi, I'm trying to embed the form in a modal window in my website so that my users can fill the form out on demand during the use of my application.  But it never allows me to see the form in the modal, just providing a link to launch it in a new window.  

Can you please provide documentation on how to show this form in a bootstrap modal or via other method to popup?  the current article for this https://docs.microsoft.com/en-us/forms-pro/embed-web-page does not accurately represent the "Embed" feature in the website anymore.  See screenshot below for the view that is provided to me in the embed feature.

![image](https://user-images.githubusercontent.com/9604991/87797167-5475d480-c818-11ea-892e-5b896c8633db.png)

**Comment by akirby** [comment]
@sbmjais

**Comment by sbmjais** [comment]
Hi @akirby - The document you are referring to is for Forms Pro. However, the image is form Microsoft Forms. The document for Forms is: https://support.microsoft.com/en-us/office/send-a-form-and-collect-responses-2eaf3294-0cff-492d-884d-a1dee909e845

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
