### ISSUE TITLE
Toggle option missing?

### ISSUE THREAD

**Issue by dbetlow** [MicrosoftDocs/forms-pro#35]
We used to have this Toggle option in the Branching for If True action, but it is no longer there.  Was it removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147c85a2-7442-d63f-789c-719a67418b75
* Version Independent ID: 5af6f725-a4b6-c414-387a-eda7e2d9a5e8
* Content: [Create a branching rule for a survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/create-branching-rule)
* Content Source: [fp-docs/create-branching-rule.md](https://github.com/MicrosoftDocs/forms-pro/blob/live/fp-docs/create-branching-rule.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for contacting us. This feature is not available. We have updated the [document ](https://docs.microsoft.com/en-us/forms-pro/create-branching-rule)accordingly.
Closing this issue.
