### ISSUE TITLE
new responses behavior when exceeding capacity

### ISSUE THREAD

**Issue by camous** [MicrosoftDocs/forms-pro#36]
`If the consumed response capacity reaches or exceeds the annual response capacity in any given month, Forms Pro will stop receiving new responses and won't allow new surveys to be created.`

what happens to new responses received if the capacity is exceeded ? are they lost or only on hold waiting either
* more capacity
* next month capacity "reset"

?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eea885c-4244-1721-36f7-6a42baca9411
* Version Independent ID: 59ced40c-3cea-298e-ee4e-38c390493c59
* Content: [Purchase Microsoft Forms Pro and additional license - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/purchase)
* Content Source: [fp-docs/purchase.md](https://github.com/MicrosoftDocs/forms-pro/blob/live/fp-docs/purchase.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
We have an updated documentation at: https://docs.microsoft.com/en-us/forms-pro/purchase#response-capacity-consumption. Please see if it answers your question. For more information, please contact Microsoft support.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
