### ISSUE TITLE
Update Doc with Dynamics Licensing Details

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/forms-pro#38]
This documentation needs to be updated with new text and screenshots as the license names have transitioned to "Dynamics 365 Customer Voice Pro USL" and "Dynamics 365 Customer Voice Addl Responses".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eea885c-4244-1721-36f7-6a42baca9411
* Version Independent ID: 59ced40c-3cea-298e-ee4e-38c390493c59
* Content: [Purchase Microsoft Forms Pro and additional license - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/purchase)
* Content Source: [fp-docs/purchase.md](https://github.com/MicrosoftDocs/forms-pro/blob/live/fp-docs/purchase.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @tseward - We have a new Customer Voice documentation with steps to purchase Customer Voice licenses - [https://docs.microsoft.com/en-us/dynamics365/customer-voice/purchase](https://docs.microsoft.com/en-us/dynamics365/customer-voice/purchase)

Hope this is helpful. Closing this issue.

**Comment by tseward** [comment]
@sbmjais can you either add a redirect or an !IMPORTANT with a link to that location?
