### ISSUE TITLE
Autodetect language

### ISSUE THREAD

**Issue by fuguet** [MicrosoftDocs/forms-pro#4]
Can be great an autodetect feature so if the user access the survey with a device/os/software in an specific language, automatic loads the related language form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4cb88d8-55a3-9e36-00c2-ab36509bd952
* Version Independent ID: 43d00b62-0c3c-332c-9f6c-047707ec3b07
* Content: [Create a multilingual survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/create-multilingual-survey#feedback)
* Content Source: [fp-docs/create-multilingual-survey.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/create-multilingual-survey.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for your feedback. For product-related feedback, visit, [https://microsoftforms.uservoice.com/forums/386451-welcome-to-microsoft-forms-suggestion-box?category_id=357997](https://microsoftforms.uservoice.com/forums/386451-welcome-to-microsoft-forms-suggestion-box?category_id=357997).
Closing this issue.
