### ISSUE TITLE
Formatting text is broken

### ISSUE THREAD

**Issue by Jonaholland** [MicrosoftDocs/forms-pro#5]
This option doesn't appear in Forms the way it's shown on this page.  Is this correct?  Can we format text in Forms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c486fb3-5db1-5d6a-45f8-b0b803fdd86f
* Version Independent ID: 10b85f4c-6388-f2c5-0101-459a1add35c0
* Content: [Format text in a survey - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/survey-text-format#feedback)
* Content Source: [fp-docs/survey-text-format.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/survey-text-format.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by EUA-ATS** [comment]
Ditto.  This option does not seem to be working.  I am in Forms Pro. When I click on eligible text, all I see are the copy, delete, move up and move down options.

**Comment by thavez** [comment]
Hi, same issue here, it's not working either. A little help ?

**Comment by Fraisouille63** [comment]
Hi @sbmjais could you please have a look again on that option :D
Thanks

**Comment by sbmjais** [comment]
Hi @Fraisouille63, I just checked Forms Pro, formatting toolbar is working fine. 
For Microsoft Forms, please contact the Forms support team.

**Comment by Fraisouille63** [comment]
@sbmjais oh thanks I didn't noticed there was two different "forms"

**Comment by andrew-hwahin** [comment]
Hi, I'm also unable to see the formatting toolbar. Also, where can I contact Forms support team?

**Comment by sbmjais** [comment]
@andrew-hwahin You can contact Forms support team through [this link](https://support.office.com/en-us/home/contact?contactUsExperienceEntryPointAssetId=S.HP.forms)

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
