### ISSUE TITLE
Specify time period purchase of "responses"

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/forms-pro#7]
This appears to be per month not per year but that is not clear in this document. Please clarify. See the first section, "For an Office 365 licensed customer, there are no free responses included. The customer has to purchase responses in bundles of $100 per 2000 responses." Over what period of time does those made available exist? Monthly? Annually?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eea885c-4244-1721-36f7-6a42baca9411
* Version Independent ID: 59ced40c-3cea-298e-ee4e-38c390493c59
* Content: [Purchase - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/purchase)
* Content Source: [fp-docs/purchase.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/purchase.md)
* Service: **forms-pro**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks @adrianwells for the feedback. We have updated the document accordingly. Closing the issue.
