### ISSUE TITLE
"Microsoft Forms" does has impact on the search results 

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/forms-pro#9]
This is rather a feedback than issue. You will get the follow results when you search for “Microsoft Forms font” in Google for example.

https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/font-object-microsoft-forms

https://www.howtoexcel.org/general/microsoft-forms/ 

https://books.google.com.my/books?id=ijM7PDa36KIC&pg=PA427&lpg=PA427&dq=microsoft+forms+font&source=bl&ots=tendLwT7v_&sig=ACfU3U3vgfRFVqUmmZBYSElXPQmwgletQA&hl=en&sa=X&ved=2ahUKEwij2r7ZqefmAhVp63MBHQgICBs4ChDoATASegQIChAB#v=onepage&q=microsoft%20forms%20font&f=false

Should there be 2 products having exactly the same name “Microsoft Forms”?

**Comment by sbmjais** [comment]
Thanks for your feedback. For product-related feedback, visit [UserVoice](https://microsoftforms.uservoice.com/forums/386451-welcome-to-microsoft-forms-suggestion-box?category_id=357997). 
Closing this issue.
